# Directories arguments
data_dir: "full_cityscapes_res"
exp_dir:  "dilationv2_mobilenet"
out_dir:  "dilationv2_mobilenet"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 4
shuffle: True
data_mode: "experiment_v2"
save_every: 10
test_every: 5
max_to_keep: 1
weighted_loss: True
freeze_encoder: False
random_cropping: False
targets_resize: 4

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True
pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

