# Directories arguments
data_dir: "full_cityscapes_res"
exp_dir:  "unet_mobilenet_exp_fixedbn"
out_dir:  "unet_mobilenet_exp_fixedbn"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: True
data_mode: "test"
save_every: 5
test_every: 5
max_to_keep: 5

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

