# Directories arguments
data_dir: "full_cityscapes_res"
exp_dir:  "unet_resnet18"
out_dir:  "unet_resnet18"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: True
data_mode: "debug"
save_every: 10
test_every: 10
max_to_keep: 1
weighted_loss: False
random_cropping: False

# Models arguments
bias: 0.0
learning_rate: 0.0001
weight_decay: 0.00005
pretrained_path: "pretrained_weights/linknet_weights.pkl"

# Misc arguments
verbose: False

